name: CI - Editor Only

on:
  push:
    branches:
      - 'DEFEDIT-*'
  # pull_request:
  #   branches:
  #     - 'DEFEDIT-*'

jobs:
  build-and-notarize-editor:
    runs-on: macOS-latest
    steps: [
      { name: 'Checkout', uses: actions/checkout@v2, with: { fetch-depth: 0 } },
      { name: 'Fetch tags', run: 'git fetch --depth=1 origin +refs/tags/*:refs/tags/*' },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Install Java', uses: actions/setup-java@v1, with: { java-version: '11.0.2' } },
      { name: 'Install Leiningen', uses: DeLaGuardo/setup-clojure@master, with: { lein: 2.8.3 } },
      {
        name: 'Install dependencies',
        env: {
            MACOS_CERTIFICATE: '${{ secrets.MACOS_CERTIFICATE }}',
            MACOS_CERTIFICATE_PASS: '${{ secrets.MACOS_CERTIFICATE_PASS }}'
        },
        run: 'ci/ci.sh --keychain-cert="${MACOS_CERTIFICATE}" --keychain-cert-pass="${MACOS_CERTIFICATE_PASS}" install'
      },
      {
        name: 'Build editor',
        env: {
            S3_ACCESS_KEY: '${{ secrets.S3_ACCESS_KEY }}',
            S3_SECRET_KEY: '${{ secrets.S3_SECRET_KEY }}',
            DM_PACKAGES_URL: '${{ secrets.DM_PACKAGES_URL }}'
        },
        run: 'ci/ci.sh --branch=$GITHUB_REF build-editor'
      },
      {
        name: 'Notarize editor',
        env: {
            S3_ACCESS_KEY: '${{ secrets.S3_ACCESS_KEY }}',
            S3_SECRET_KEY: '${{ secrets.S3_SECRET_KEY }}',
            NOTARIZATION_USERNAME: '${{ secrets.NOTARIZATION_USERNAME }}',
            NOTARIZATION_PASSWORD: '${{ secrets.NOTARIZATION_PASSWORD }}',
            NOTARIZATION_ITC_PROVIDER: '${{ secrets.NOTARIZATION_ITC_PROVIDER }}',
            DM_PACKAGES_URL: '${{ secrets.DM_PACKAGES_URL }}'
        },
        run: 'ci/ci.sh --branch=$GITHUB_REF --notarization-username="${NOTARIZATION_USERNAME}" --notarization-password="${NOTARIZATION_PASSWORD}" --notarization-itc-provider="${NOTARIZATION_ITC_PROVIDER}" notarize-editor'
      },
      {
        name: 'Archive editor',
        env: {
            S3_ACCESS_KEY: '${{ secrets.S3_ACCESS_KEY }}',
            S3_SECRET_KEY: '${{ secrets.S3_SECRET_KEY }}',
            DM_PACKAGES_URL: '${{ secrets.DM_PACKAGES_URL }}'
        },
        run: 'ci/ci.sh --branch=$GITHUB_REF archive-editor'
      }]
