name: CI - Editor Only

on:
  push:
    branches:
      - test_ci
      # - 'DEFEDIT-*'

jobs:
  build-and-test-editor:
    runs-on: macOS-10.14
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x86 } },
      { name: 'Build editor', run: 'python ci/ci.py --branch=$GITHUB_REF install editor' },
      { name: 'Smoke test editor', run: 'python ci/ci.py --branch=$GITHUB_REF install smoke' }]
