name: CI

on:
  schedule:
    # nightly at 03:00
    - cron: 0 3 * * *

jobs:
  build-engine-darwin-64:
    runs-on: macOS-10.14
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1, ref: dev } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Build engine', run: 'python ci/ci.py --platform=x86_64-darwin --branch=dev --with-asan --with-vanilla-lua install engine' }]

  build-engine-linux-64:
    runs-on: ubuntu-18.04
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1, ref: dev } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Build engine', run: 'python ci/ci.py --platform=x86_64-linux --branch=dev --with-valgrind --with-vanilla-lua install engine' }]
