name: CI - Main

on:
  push:
    branches:
      - 'hotfix-*'
      - 'dev'
      - 'beta'
      - 'master'
  pull_request:
    branches:
       - '*'
       - '!skip-ci-*'
       - '!DEFEDIT-*'
       - '!editor-dev'
  pull_request_target:
    branches:
       - '*'
       - '!skip-ci-*'
       - '!DEFEDIT-*'
       - '!editor-dev'
    types: [labeled]
  repository_dispatch: {}

env:
  S3_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY }}
  S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
  NOTARIZATION_USERNAME: ${{ secrets.NOTARIZATION_USERNAME }}
  NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
  NOTARIZATION_ITC_PROVIDER: ${{ secrets.NOTARIZATION_ITC_PROVIDER }}
  DM_PACKAGES_URL: ${{ secrets.DM_PACKAGES_URL }}
  DM_ARCHIVE_DOMAIN: ${{ secrets.DM_ARCHIVE_DOMAIN }}
  DM_RELEASE_REPOSITORY: ${{ secrets.DM_RELEASE_REPOSITORY }}
  WINDOWS_CERTIFICATE: ${{ secrets.WINDOWS_CERTIFICATE }}
  WINDOWS_CERTIFICATE_PASS: ${{ secrets.WINDOWS_CERTIFICATE_PASS }}
  MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
  MACOS_CERTIFICATE_PASS: ${{ secrets.MACOS_CERTIFICATE_PASS }}
  BUILD_BRANCH: ${{ github.event.client_payload.branch }}
  SERVICES_GITHUB_TOKEN: ${{ secrets.SERVICES_GITHUB_TOKEN }}
  DEFOLD_EDITOR_DISABLE_PERFORMANCE_TESTS: true


jobs:
# ---- PRE-CHECK
# ---- * Do not proceed if commit message contains "skip-ci"
# ---- * If workflow is started from a "pull_request" event only proceed if coming from the Defold org
# ---- * If workflow is started from a "pull_equest_target" event only proceed if it has the label "ok to test"
  pre-check:
    runs-on: ubuntu-20.04
    if: |
      !contains(github.event.head_commit.message, 'skip-ci') &&
      (github.event_name != 'pull_request'        || (github.event_name == 'pull_request'        && github.event.pull_request.head.repo.full_name == github.repository)) &&
      (github.event_name != 'pull_request_target' || (github.event_name == 'pull_request_target' && contains(github.event.pull_request.labels.*.name, 'ok to test')))
    steps: [
      {
        shell: bash,
        run: 'echo "Pre-check ok"'
      }]

# ---- BUILD ENGINE VERSIONS ------------------
    bld-eng-macos-64:
    runs-on: macOS-latest
    steps: [
      { name: 'Checkout', uses: actions/checkout@v2 },
      { name: 'Install Python', uses: actions/setup-python@v2, with: { python-version: 3.x, architecture: x64 } },
      { name: 'Install Java', uses: actions/setup-java@v3, with: { java-version: '11.0.15', distribution: 'microsoft'} },
      { name: 'Install dependencies', run: 'ci/ci.sh install' },
      {
        name: 'ASAN',
        run: 'ci/ci.sh --platform=x86_64-macos --with-asan --skip-builtins --skip-docs engine'
      },
      {
         name: 'Notify if build status changed',
         uses: homoluctus/slatify@master,
         if: failure(),
         with: { type: '${{ job.status }}', job_name: '${{ job.status }}', channel: '#defold-alarms-build', url: '${{ secrets.SLACK_WEBHOOK }}',
               mention: 'here', mention_if: 'failure', commit: true, token: '${{ secrets.SERVICES_GITHUB_TOKEN }}' }
      }]
