name: CI

on:
  push:
    branches:
      - test_ci

jobs:
  build-engine:
    strategy:
      matrix:
        os: [macOS-10.14, windows-2016, ubuntu-18.04]
        platform: [linux-64, win32, win32-64, darwin-64, ios, ios-64, ios-simulator, android, android-64, js-web, wasm-web]
        exclude:
          - os: macOS-10.14
            platform: [linux-64, win32, win32-64, android, android-64, js-web, wasm-web]
          - os: windows-2016
            platform: [linux-64, darwin-64, ios, ios-64, ios-simulator, android, android-64, js-web, wasm-web]
          - os: ubuntu-18.04
            platform: [win32, win32-64, darwin-64, ios, ios-64, ios-simulator, android, android-64]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Build engine
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
      uses: actions/setup-python@v1
      with:
        python-version: '2.x'
        architecture: 'x64'
      run: python ci/ci.py --platform=${{ matrix.platform }} --branch=${GITHUB_REF} install engine

