name: CI

on:
  push:
    branches:
      - test_ci
      - '!DEFEDIT-*'

jobs:
  build-engine-on-macos:
    strategy:
      matrix:
        platform: [darwin-64, ios, ios-64, ios-simulator]
    runs-on: macOS-10.14
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Install dependencies', run: 'python ci/ci.py install' },
      { name: 'Build engine', run: 'python ci/ci.py --platform=${{ matrix.platform }} --branch=$GITHUB_REF engine' }]

  build-engine-on-windows:
    strategy:
      matrix:
        platform: [win32, win32-64]
    runs-on: windows-2016
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x86 } },
      { name: 'Install dependencies', run: 'python ci/ci.py install' },
      { name: 'Build engine', run: 'python ci/ci.py --platform=${{ matrix.platform }} --branch=$GITHUB_REF engine' }]

  build-engine-on-linux:
    strategy:
      matrix:
        platform: [linux-64, android, android-64, js-web, wasm-web]
    runs-on: ubuntu-18.04
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Install dependencies', run: 'python ci/ci.py install' },
      { name: 'Build engine', run: 'python ci/ci.py --platform=${{ matrix.platform }} --branch=$GITHUB_REF engine' }]

  build-bob:
    needs: [build-engine-on-macos, build-engine-on-windows, build-engine-on-linux]
    runs-on: ubuntu-18.04
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Install dependencies', run: 'python ci/ci.py install' },
      { name: 'Build bob', run: 'python ci/ci.py --branch=$GITHUB_REF bob' }]
  
  build-sdk:
    needs: [build-engine-on-macos, build-engine-on-windows, build-engine-on-linux]
    runs-on: ubuntu-18.04
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Install dependencies', run: 'python ci/ci.py install' },
      { name: 'Build SDK', run: 'python ci/ci.py --branch=$GITHUB_REF sdk' }]
  
  build-editor-and-smoke-test:
    needs: [build-bob,build-sdk]
    runs-on: macOS-10.14
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x64 } },
      { name: 'Install dependencies', run: 'python ci/ci.py install' },
      { name: 'Build editor', run: 'python ci/ci.py --branch=$GITHUB_REF editor' },
      { name: 'Smoke-test', run: 'python ci/ci.py --branch=$GITHUB_REF smoke' }]
