name: CI - Main

on:
  push:
    branches:
    - 'github-ci-fixes'
  pull_request:
    branches:
    - 'github-ci-fixes'

jobs:
# ---- BUILD ENGINE VERSIONS ------------------
  build-engine-windows:
    strategy:
      matrix:
        platform: [win32, x86_64-win32]
    runs-on: windows-2016
    steps: [
      { name: 'Checkout', uses: actions/checkout@v1, with: { fetch-depth: 1 } },
      { name: 'Install Python', uses: actions/setup-python@v1, with: { python-version: 2.x, architecture: x86 } },
      { name: 'Install dependencies', run: 'python ci/ci.py install' },
      { name: 'Build engine', env: { S3_ACCESS_KEY: '${{ secrets.S3_ACCESS_KEY }}', S3_SECRET_KEY: '${{ secrets.S3_SECRET_KEY }}' }, run: 'python ci/ci.py --platform=${{ matrix.platform }} --branch=$GITHUB_REF --archive --skip-builtins --skip-docs engine' }]
